[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
serde_json = "1.0"
sha2 = "0.10"
sha3 = "0.10"
hex = "0.4"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.41", features = ["full"] }