[package]
name = "competiton"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "1.2.0", features = ["prove"] }
serde = "1.0"
sha2 = "0.10"
sha3 = "0.10"
hex = "0.4"
reqwest = "0.12"
tokio = { version = "1.41", features = ["full"] }